### ISSUE TITLE
Move to 'spec'

### ISSUE THREAD

**Issue by bates64** [haumea-lang/spec#6]
Since these are design issues, this would be more suited to haumea-lang/spec.

**Comment by BookOwl** [comment]
I was thinking that this would be for brainstorming ideas, and then when they are ready they could be added to the spec.

**Comment by bates64** [comment]
However the ideas are for the spec, right?
It makes more sense to gradually add to the spec as we go and use branches for versions, keeping _issues_ on that same repo for any issues or discussions.

**Comment by bates64** [comment]
Having an entire repo dedicated to gh issues seems a bit pointless.

**Comment by BookOwl** [comment]
OK, I'll change this into the spec repo and delete the other one.
